# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "064330ac8f15b8c165d3ea3348bd76a5"
name = "test-app-sharuga-suthakaran"
handle = "test-app-sharuga-suthakaran"
application_url = "https://kerry-sig-benjamin-sudan.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_product_listings"

[auth]
redirect_urls = [
  "https://kerry-sig-benjamin-sudan.trycloudflare.com/auth/callback",
  "https://kerry-sig-benjamin-sudan.trycloudflare.com/auth/shopify/callback",
  "https://kerry-sig-benjamin-sudan.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
